export const FIRM_CONTACTS = [
  { firm: 'FTMO', type: 'Affiliate Portal', contact: 'https://ftmo.com/en/affiliate-programme/', note: 'Apply via portal — no direct email' },
  { firm: 'The5ers', type: 'Affiliate Email', contact: 'affiliates@the5ers.com', note: '10% commission' },
  { firm: 'FundedNext', type: 'Affiliate Email', contact: 'affiliate@fundednext.com', note: 'Up to 15% commission' },
  { firm: 'FundingPips', type: 'Partnerships Email', contact: 'partners@fundingpips.com', note: '20% commission available' },
  { firm: 'Alpha Capital', type: 'Support Email', contact: 'support@alphacapitalgroup.uk', note: 'Contact support for affiliate' },
  { firm: 'Topstep', type: 'Affiliate Portal', contact: 'https://www.topstep.com/affiliates/', note: 'Apply via portal' },
  { firm: 'Apex Trader Funding', type: 'Affiliate Email', contact: 'affiliates@apextraderfunding.com', note: 'Strong promo program' },
  { firm: 'E8 Markets', type: 'Affiliate Email', contact: 'affiliate@e8markets.com', note: 'Good commission rates' },
  { firm: 'FXIFY', type: 'Partnerships Email', contact: 'partners@fxify.com', note: 'Active affiliate program' },
  { firm: 'Maven Trading', type: 'Support Email', contact: 'support@maventrading.com', note: 'Ask about affiliate' },
  { firm: 'Smart Prop Trader', type: 'Affiliate Email', contact: 'affiliate@smartproptrader.com', note: '25% commission' },
  { firm: 'Goat Funded Trader', type: 'Affiliate Email', contact: 'affiliates@goatfundedtrader.com', note: 'Frequent big promos' },
  { firm: 'Funded Trading Plus', type: 'Affiliate Email', contact: 'affiliates@fundedtradingplus.com', note: 'Up to 20% commission' },
  { firm: 'Hola Prime', type: 'Support Email', contact: 'support@holaprime.com', note: 'Ask about partnerships' },
  { firm: 'Blueberry Funded', type: 'Affiliate Email', contact: 'affiliate@blueberryfunded.com', note: 'Regulated broker backed' },
  { firm: 'BrightFunded', type: 'Partnerships Email', contact: 'partners@brightfunded.com', note: 'New firm, open to deals' },
  { firm: 'For Traders', type: 'Support Email', contact: 'support@fortraders.com', note: 'EU-regulated firm' },
  { firm: 'Moneta Funded', type: 'Affiliate Email', contact: 'affiliate@monetafunded.com', note: 'New firm, active outreach' },
  { firm: 'The Trading Pit', type: 'Partnerships Email', contact: 'partners@thetradingpit.com', note: 'Liechtenstein-licensed' },
  { firm: 'Traders With Edge', type: 'Support Email', contact: 'support@traderswithededge.com', note: 'UK firm' },
  { firm: 'Audacity Capital', type: 'Support Email', contact: 'support@audacitycapital.co.uk', note: 'UK-based' },
  { firm: 'City Traders Imperium', type: 'Affiliate Email', contact: 'affiliates@citytraders.com', note: '20% commission' },
  { firm: 'DNA Funded', type: 'Affiliate Email', contact: 'affiliate@dnafunded.com', note: 'AU-based, growing fast' },
]